version: '3.9'

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=plex.lvh.me
      - TZ=Australia/Sydney
    hostname: plex.lvh.me
    volumes:
      - ./provision/plex:/config
      - ./content/media:/data/media
    ports:
      - 32400/tcp
      - 32400/udp
      - 3005/tcp
      - 8324/tcp
      - 32469/tcp
      - 1900/udp
      - 32410/udp
      - 32412/udp
      - 32413/udp
      - 32414/udp
    privileged: true # libusb_init failed
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.entrypoints=web-secure
      - traefik.http.routers.plex.rule=(Host(`plex.lvh.me`))
      - traefik.http.services.plex.loadbalancer.server.port=32400
    networks:
      - traefik-reverse-proxy_default

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/radarr:/config
      - ./content:/data
    ports:
      - 7878
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.movies.tls=true
      - traefik.http.routers.movies.entrypoints=web-secure
      - traefik.http.routers.movies.rule=(Host(`movies.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/sonarr:/config
      - ./content:/data
    ports:
      - 8989
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tv.tls=true
      - traefik.http.routers.tv.entrypoints=web-secure
      - traefik.http.routers.tv.rule=(Host(`tv.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/lidarr:/config
      - ./content:/data
    ports:
      - 8686
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.music.tls=true
      - traefik.http.routers.music.entrypoints=web-secure
      - traefik.http.routers.music.rule=(Host(`music.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/prowlarr:/config
    ports:
      - 9696
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.indexer-proxy.tls=true
      - traefik.http.routers.indexer-proxy.entrypoints=web-secure
      - traefik.http.routers.indexer-proxy.rule=(Host(`indexer-proxy.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/bazarr:/config
      - ./content:/data
    ports:
      - 6767
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.subtitles.tls=true
      - traefik.http.routers.subtitles.entrypoints=web-secure
      - traefik.http.routers.subtitles.rule=(Host(`subtitles.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/qbittorrent:/config
      - ./content/torrents:/data/torrents
    ports:
      - 8080
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrent.tls=true
      - traefik.http.routers.torrent.entrypoints=web-secure
      - traefik.http.routers.torrent.rule=(Host(`torrent.lvh.me`))
      - traefik.http.services.torrent.loadbalancer.server.port=8080
    networks:
      - traefik-reverse-proxy_default

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/ombi:/config
    ports:
      - 3579
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.request-media.tls=true
      - traefik.http.routers.request-media.entrypoints=web-secure
      - traefik.http.routers.request-media.rule=(Host(`request-media.lvh.me`))
    networks:
      - traefik-reverse-proxy_default

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./provision/heimdall:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.tls=true
      - traefik.http.routers.heimdall.entrypoints=web-secure
      - traefik.http.routers.heimdall.rule=(Host(`localflix.lvh.me`))
    ports:
      - 80
    restart: unless-stopped
    networks:
      - traefik-reverse-proxy_default

networks:
  traefik-reverse-proxy_default:
    external: true
